name: Build and deploy React app to Azure Web App - ucb-factory-admin-dev

env:
  NODE_VERSION: '22.x'
  AZURE_WEBAPP_NAME: 'ucb-factory-admin-dev'

on:
  push:
    branches:
      - admin/dev
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test

  quality-check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Security Audit
        run: npm audit --production --audit-level=high

      - name: Type Check
        run: npm run type-check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://ucb-factory-api-dev-h7h2bab7g3eee5ed.uaenorth-01.azurewebsites.net/api/v1' }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME || 'UCB Factory Admin' }}
          VITE_AZURE_TENANT_ID: ${{ secrets.VITE_AZURE_TENANT_ID }}
          VITE_AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_CLIENT_ID }}
          VITE_AZURE_REDIRECT_URI: ${{ secrets.VITE_AZURE_REDIRECT_URI || 'https://ucb-factory-admin-dev.azurewebsites.net/auth/callback' }}

      - name: Prepare deploy package
        run: |
          rm -rf deploy
          mkdir -p deploy
          # Copy dist folder
          cp -R dist deploy/
          # Copy server.js for Azure Web App
          cp server.js deploy/
          # Create minimal package.json for production server
          cat > deploy/package.json << 'EOF'
          {
            "name": "ucb-factory-admin-web",
            "version": "1.0.0",
            "type": "module",
            "scripts": {
              "start": "node server.js"
            },
            "dependencies": {
              "express": "^4.18.2"
            },
            "engines": {
              "node": ">=22.0.0"
            }
          }
          EOF
          # Install only production dependencies for server
          cd deploy
          npm install --production
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: deploy
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, quality-check-code, build]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: react-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ./react-app
